#!/bin/bash

set -e
source "${PERLBREW_ROOT}/etc/bashrc"
echo "Installing perl dependencies ..."
perlbrew use "${perl_version}"
if [ -f cpanfile ]; then
	cpanm --notest -L "./.local" --installdeps --skip-satisfied .
else
	echo "cpanfile not found!"
fi

